/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.main.client;

import controllers.Client.DangKyHopDong;
import database.ConnectDB;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.io.File;
import java.util.UUID;
import models.DataGlobal;
import models.HopDongModel;
import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.net.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;

/**
 *
 * @author GIANG
 */
public class HopDongDangKy extends javax.swing.JFrame {

    /**
     * Creates new form HopDongDangKy
     */
    private CloudinaryUploader uploader;

    private String linkCCCD;
    private String linkGiayTo;

    public String linkChuKy = DataGlobal.getDataGLobal.dataGlobal.getLinkChuKy();

    public HopDongDangKy() {
        initComponents();
        displayImage();
        loadDataToMucDichSuDungComboBox();
        loadDataToDiaChiComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        DiaChiEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SoDienThoai = new javax.swing.JTextField();
        SoNha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Ngo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        MucDichSuDungCombox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ChonCCCD = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TenKhachHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CCCD = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ChonSoDo = new javax.swing.JButton();
        TaoChuKy = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        statusLabel2 = new javax.swing.JLabel();
        phuongCombobox = new javax.swing.JComboBox<>();
        displayImg = new javax.swing.JLabel();
        GuiYeuCau = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("* Khách hàng cam kết các thông tin kê khai trên là đầy đủ, chính xác");

        jLabel7.setText("Địa chỉ Email");

        jLabel17.setText(" và đồng ý với quy định cung cấp dịch vụ của Công ty");

        jLabel8.setText("Số điện thoại (*)");

        jLabel9.setText("Địa chỉ lắp đặt (*)");

        Ngo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NgoActionPerformed(evt);
            }
        });

        jLabel10.setText("Mục đích sử dụng");

        MucDichSuDungCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        MucDichSuDungCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MucDichSuDungComboxActionPerformed(evt);
            }
        });

        jLabel18.setText("Chữ ký điện tử");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("2. ĐÍNH KÈM HỒ SƠ");

        jLabel12.setText("Giấy tờ tùy thân:");

        jLabel13.setText("CCCD/CMTND");

        ChonCCCD.setBackground(new java.awt.Color(51, 153, 255));
        ChonCCCD.setForeground(new java.awt.Color(255, 255, 255));
        ChonCCCD.setText("Chọn tệp");
        ChonCCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChonCCCDActionPerformed(evt);
            }
        });

        jLabel14.setText("Giấy tờ đăng kí kèm theo:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cấp nước hộ gia đình");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("1. THÔNG TIN ĐĂNG KÝ DỊCH VỤ");

        jLabel3.setText("Tên chủ hộ/chủ sở hữu nhà(*)");

        TenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenKhachHangActionPerformed(evt);
            }
        });

        jLabel4.setText("CCCD/CMTND (*)");

        jLabel15.setText("Giấy chứng nhận sử dụng đất");

        ChonSoDo.setBackground(new java.awt.Color(0, 153, 255));
        ChonSoDo.setForeground(new java.awt.Color(255, 255, 255));
        ChonSoDo.setText("Chọn tệp");
        ChonSoDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChonSoDoActionPerformed(evt);
            }
        });

        TaoChuKy.setBackground(new java.awt.Color(0, 153, 255));
        TaoChuKy.setForeground(new java.awt.Color(255, 255, 255));
        TaoChuKy.setText("Tạo");
        TaoChuKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaoChuKyActionPerformed(evt);
            }
        });

        statusLabel.setText("File đang chọn");

        statusLabel2.setText("File đang chọn ");

        phuongCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        phuongCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phuongComboboxActionPerformed(evt);
            }
        });

        displayImg.setText("Chữ Ký");

        GuiYeuCau.setBackground(new java.awt.Color(0, 153, 204));
        GuiYeuCau.setForeground(new java.awt.Color(255, 255, 255));
        GuiYeuCau.setText("Gửi yêu cầu");
        GuiYeuCau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuiYeuCauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(TaoChuKy))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(statusLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(GuiYeuCau))
                                            .addGap(203, 203, 203)
                                            .addComponent(displayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(25, 25, 25))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TenKhachHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(71, 71, 71)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(DiaChiEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(71, 71, 71)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(MucDichSuDungCombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Ngo))))
                                            .addGap(47, 47, 47))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(SoNha, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(ChonCCCD)))
                                                    .addGap(123, 123, 123)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addComponent(jLabel15)
                                    .addGap(18, 18, 18)
                                    .addComponent(ChonSoDo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(630, 630, 630)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phuongCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(206, 206, 206))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DiaChiEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MucDichSuDungCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoNha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ngo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phuongCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(ChonCCCD)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(ChonSoDo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(statusLabel2))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(TaoChuKy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(54, 54, 54)
                        .addComponent(GuiYeuCau))
                    .addComponent(displayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuiYeuCauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuiYeuCauActionPerformed
        // TODO add your handling code here:
        String maHopDong = "HD" + UUID.randomUUID().toString().substring(0, 12);
        String tenHopDong = "Hop Dong Dang Ky Su Dung Nuoc Sach";
        String tenKhachHang = TenKhachHang.getText();
        String soDienThoai = SoDienThoai.getText();
        String cccd = CCCD.getText();
        String email = DiaChiEmail.getText();
        //        String loaiNuoc = String.valueOf(MucDichSuDungCombox.getSelectedItem());
        
        
        String loaiNuoc = "";
        
        if (MucDichSuDungCombox.getSelectedItem().equals("Nước dân dụng")) {
            loaiNuoc = "NL1";
        }


        String diaChiLapDat = SoNha.getText() + "/" + Ngo.getText() + "/" + phuongCombobox.getSelectedItem();

        String trangThai = "DANGCHODUYET";

        if (tenKhachHang.isEmpty() || soDienThoai.isEmpty() || cccd.isEmpty() || email.isEmpty() || loaiNuoc.isEmpty() || diaChiLapDat.isEmpty()) {
            // Display an error message to the user
            JOptionPane.showMessageDialog(this, "Bạn chưa điền đầy đủ thông tin!", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method
        }

        HopDongModel hopDongModel = new HopDongModel(maHopDong, tenHopDong, tenKhachHang, email, diaChiLapDat, linkCCCD, linkGiayTo, linkChuKy, trangThai, soDienThoai, cccd, loaiNuoc);

        try {
            DangKyHopDong.themHopDong(hopDongModel);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_GuiYeuCauActionPerformed

    private void phuongComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phuongComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phuongComboboxActionPerformed

    private void TaoChuKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaoChuKyActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Chữ Ký Điện Tử");
        ChuKyDienTuPanel chuKyPanel = new ChuKyDienTuPanel();
        JButton saveButton = new JButton("Lưu Chữ Ký");
        JButton clearButton = new JButton("Làm Sạch");

        saveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                chuKyPanel.saveSignatureAsImage();
                frame.dispose(); // Đóng JFrame sau khi lưu
                String linkChuKy = DataGlobal.getDataGLobal.dataGlobal.getLinkChuKy();
                System.out.println(".actionPerformed()" + linkChuKy);
                displayImage();

            }
        });

        clearButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                chuKyPanel.clearSignature();
            }
        });

        JPanel buttonPanel = new JPanel();
        buttonPanel.add(saveButton);
        buttonPanel.add(clearButton);

        frame.setLayout(new BorderLayout());
        frame.add(chuKyPanel, BorderLayout.CENTER);
        frame.add(buttonPanel, BorderLayout.SOUTH);
        frame.setSize(250, 150);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Đặt JFrame để đóng khi tắt cửa sổ
        frame.setLocationRelativeTo(this); // Hiển thị cửa sổ ở giữa cửa sổ cha
        frame.setVisible(true);

    }//GEN-LAST:event_TaoChuKyActionPerformed

    private void ChonSoDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChonSoDoActionPerformed
        // TODO add your handling code here:
        uploader = new CloudinaryUploader();

        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            statusLabel2.setText("Uploading...");
            // Upload file lên Cloudinary
            String publicUrl = uploader.uploadFile(selectedFile);
            linkGiayTo = publicUrl;
            if (publicUrl != null) {
                statusLabel2.setText("Upload successful: " + publicUrl.substring(0, 12) + "...");
            } else {
                statusLabel2.setText("Upload failed");
            }
        }
    }//GEN-LAST:event_ChonSoDoActionPerformed

    private void TenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenKhachHangActionPerformed

    private void ChonCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChonCCCDActionPerformed
        // TODO add your handling code here:

        uploader = new CloudinaryUploader();

        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            statusLabel.setText("Uploading...");
            // Upload file lên Cloudinary
            String publicUrl = uploader.uploadFile(selectedFile);

            linkCCCD = publicUrl;
            if (publicUrl != null) {
                statusLabel.setText("Upload successful: " + publicUrl.substring(0, 12) + "...");
            } else {
                statusLabel.setText("Upload failed");
            }
        }
    }//GEN-LAST:event_ChonCCCDActionPerformed

    private void NgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NgoActionPerformed

    private void MucDichSuDungComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MucDichSuDungComboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MucDichSuDungComboxActionPerformed

    private void loadDataToMucDichSuDungComboBox() {
        // Sử dụng try-with-resources để tự động đóng các tài nguyên
        try {
            // Kết nối tới cơ sở dữ liệu
            Connection conn = ConnectDB.getConnection();

            // Chuỗi truy vấn để lấy tên các loại từ bảng LOAI
            String query = "SELECT TENLOAI FROM LOAI";

            try {
                PreparedStatement statement = conn.prepareStatement(query);
                ResultSet resultSet = statement.executeQuery();
                // Xóa các mục cũ trong JComboBox trước khi thêm các mục mới
                MucDichSuDungCombox.removeAllItems();

                // Lặp qua kết quả và thêm vào JComboBox
                while (resultSet.next()) {
                    String tenLoai = resultSet.getString("TENLOAI");
                    MucDichSuDungCombox.addItem(tenLoai);
                }
            } catch (SQLException e) {
                // In lỗi ra console
                e.printStackTrace();
            } finally {
                // Đảm bảo rằng kết nối được đóng sau khi sử dụng
                if (conn != null) {
                    try {
                        conn.close();
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                }
            }
        } catch (SQLException | ClassNotFoundException e) {
            // Xử lý ClassNotFoundException và SQLException
            e.printStackTrace();
        }
    }
    
     private void loadDataToDiaChiComboBox() {
        // Sử dụng try-with-resources để tự động đóng các tài nguyên
        try {
            // Kết nối tới cơ sở dữ liệu
            Connection conn = ConnectDB.getConnection();

            // Chuỗi truy vấn để lấy tên các loại từ bảng LOAI
            String query = "SELECT TENKHUVUC FROM KHUVUC";

            try {
                PreparedStatement statement = conn.prepareStatement(query);
                ResultSet resultSet = statement.executeQuery();
                // Xóa các mục cũ trong JComboBox trước khi thêm các mục mới
                phuongCombobox.removeAllItems();

                // Lặp qua kết quả và thêm vào JComboBox
                while (resultSet.next()) {
                    String tenLoai = resultSet.getString("TENKHUVUC");
                    phuongCombobox.addItem(tenLoai);
                }
            } catch (SQLException e) {
                // In lỗi ra console
                e.printStackTrace();
            } finally {
                // Đảm bảo rằng kết nối được đóng sau khi sử dụng
                if (conn != null) {
                    try {
                        conn.close();
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                }
            }
        } catch (SQLException | ClassNotFoundException e) {
            // Xử lý ClassNotFoundException và SQLException
            e.printStackTrace();
        }
    }

    private void displayImage() {
        // Thay đổi hình ảnh của JLabel đã tồn tại
        try {
            // Đảm bảo linkChuKy có giao thức hợp lệ
            String imagePath = DataGlobal.getDataGLobal.dataGlobal.getLinkChuKy();
            if (!imagePath.startsWith("http://") && !imagePath.startsWith("https://")) {
                imagePath = "http://" + imagePath; // Thêm giao thức mặc định nếu không có
            }

            // Tạo một ImageIcon từ URL
            ImageIcon icon = new ImageIcon(new URL(imagePath));

            // Thay đổi hình ảnh của JLabel đã tồn tại
            displayImg.setIcon(icon);

            // Cập nhật lại giao diện để hiển thị hình ảnh mới
            displayImg.revalidate();
            displayImg.repaint();
        } catch (MalformedURLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "URL không hợp lệ: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tải hình ảnh: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HopDongDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HopDongDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HopDongDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HopDongDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HopDongDangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCCD;
    private javax.swing.JButton ChonCCCD;
    private javax.swing.JButton ChonSoDo;
    private javax.swing.JTextField DiaChiEmail;
    private javax.swing.JButton GuiYeuCau;
    private javax.swing.JComboBox<String> MucDichSuDungCombox;
    private javax.swing.JTextField Ngo;
    private javax.swing.JTextField SoDienThoai;
    private javax.swing.JTextField SoNha;
    private javax.swing.JButton TaoChuKy;
    private javax.swing.JTextField TenKhachHang;
    private javax.swing.JLabel displayImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> phuongCombobox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusLabel2;
    // End of variables declaration//GEN-END:variables
}
