/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.main.Manager;

import controllers.Manager.PhanCongCtrl;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.DataGlobal;
import models.KhuVucModel;

/**
 *
 * @author GIANG
 */
public class TrangPhanCong extends javax.swing.JPanel {

    /**
     * Creates new form TrangPhanCong
     */
    DefaultTableModel tableModel;
    List<KhuVucModel> listKhuVuc = new ArrayList<>();

    private String idArea;

    private int selectedIndex;
    public TrangPhanCong() {
        try {
            initComponents();

            tableModel = (DefaultTableModel) listAreaTable.getModel();

            hienThiDSKhuvuc();

            selectedIndex = listAreaTable.getSelectedRow();
            
            System.out.println("selectedIndex " + selectedIndex);

            updateArea.setEnabled(false);
            deleteArea.setEnabled(false);
            detailAreaAssignment.setEnabled(false);


        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLiNhanVienView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public void hienThiDSKhuvuc() throws ClassNotFoundException {

        listKhuVuc = PhanCongCtrl.timTatCaKhuVuc();

        tableModel.setRowCount(0);

        listKhuVuc.forEach(area -> {
            tableModel.addRow(new Object[]{area.getMAKHUVUC(), area.getTENKHUVUC()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addArea = new javax.swing.JButton();
        updateArea = new javax.swing.JButton();
        deleteArea = new javax.swing.JButton();
        reloadArea = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAreaTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldNameArea = new javax.swing.JTextField();
        detailAreaAssignment = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(235, 239, 254));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(43, 54, 116));
        jLabel1.setText("Khu vực ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 205, 153));
        jLabel2.setText("Công ti dịch vụ nước đô thị Quận 9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(724, 520));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Danh sách phường / xã / thị trấn Quận 9");

        addArea.setBackground(new java.awt.Color(0, 153, 255));
        addArea.setForeground(new java.awt.Color(255, 255, 255));
        addArea.setText("Thêm");
        addArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAreaActionPerformed(evt);
            }
        });

        updateArea.setBackground(new java.awt.Color(0, 153, 255));
        updateArea.setForeground(new java.awt.Color(255, 255, 255));
        updateArea.setText("Chỉnh sửa");
        updateArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAreaActionPerformed(evt);
            }
        });

        deleteArea.setBackground(new java.awt.Color(0, 153, 255));
        deleteArea.setForeground(new java.awt.Color(255, 255, 255));
        deleteArea.setText("Xóa");
        deleteArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAreaActionPerformed(evt);
            }
        });

        reloadArea.setBackground(new java.awt.Color(0, 153, 255));
        reloadArea.setForeground(new java.awt.Color(255, 255, 255));
        reloadArea.setText("Làm mới");
        reloadArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadAreaActionPerformed(evt);
            }
        });

        listAreaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã khu vực", "Tên khu vực"
            }
        ));
        listAreaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listAreaTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listAreaTable);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Phiếu thêm khu vực");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tên Khu vực");

        detailAreaAssignment.setBackground(new java.awt.Color(0, 153, 255));
        detailAreaAssignment.setForeground(new java.awt.Color(255, 255, 255));
        detailAreaAssignment.setText("Xem chi tiết");
        detailAreaAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailAreaAssignmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNameArea, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(484, 484, 484))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addArea)
                        .addGap(18, 18, 18)
                        .addComponent(updateArea)
                        .addGap(18, 18, 18)
                        .addComponent(deleteArea)
                        .addGap(18, 18, 18)
                        .addComponent(detailAreaAssignment)
                        .addGap(18, 18, 18)
                        .addComponent(reloadArea)
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addArea)
                    .addComponent(updateArea)
                    .addComponent(deleteArea)
                    .addComponent(detailAreaAssignment)
                    .addComponent(reloadArea))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAreaActionPerformed
        // TODO add your handling code here:
        String nameArea = fieldNameArea.getText();

        if (nameArea.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Trường dữ liệu không được để trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                PhanCongCtrl.themKhuvuc(nameArea);
                JOptionPane.showMessageDialog(null, "Tạo khu vực thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi tạo khu vực", "Lỗi", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_addAreaActionPerformed

    private void updateAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAreaActionPerformed
        // TODO add your handling code here:
        String nameArea = fieldNameArea.getText();

        if (nameArea.isEmpty() || idArea.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Trường dữ liệu không được để trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                PhanCongCtrl.CapNhatKhuvuc(idArea, nameArea);
                JOptionPane.showMessageDialog(null, "Cập nhật khu vực thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi cập nhật khu vực", "Lỗi", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateAreaActionPerformed

    private void deleteAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAreaActionPerformed
        // TODO add your handling code here:
        if (idArea.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Trường dữ liệu không được để trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                PhanCongCtrl.XoaKhuvuc(idArea);
                JOptionPane.showMessageDialog(null, "Xóa khu vực thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Xảy ra lỗi khi xóa khu vực", "Lỗi", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_deleteAreaActionPerformed

    private void reloadAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadAreaActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            hienThiDSKhuvuc();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLiNhanVienView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reloadAreaActionPerformed

    private void listAreaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAreaTableMouseClicked
        // TODO add your handling code here:
        selectedIndex = listAreaTable.getSelectedRow();

        if (selectedIndex == -1) {
            updateArea.setEnabled(false);
            deleteArea.setEnabled(false);
            detailAreaAssignment.setEnabled(false);
        } else {
            updateArea.setEnabled(true);
            deleteArea.setEnabled(true);
            detailAreaAssignment.setEnabled(true);
        }

        // Kiểm tra xem người dùng đã chọn một dòng hợp lệ hay không
        if (selectedIndex >= 0) {
            try {
                // Lấy đối tượng PersonModel từ danh sách listWorker

                KhuVucModel khuVucModel = listKhuVuc.get(selectedIndex);

                System.out.println(khuVucModel);

                fieldNameArea.setText(khuVucModel.getTENKHUVUC());

                idArea = khuVucModel.getMAKHUVUC();

                DataGlobal.getDataGLobal.dataGlobal.setKhuVucModel(khuVucModel);

            } catch (IndexOutOfBoundsException ex) {
                // Xử lý ngoại lệ IndexOutOfBoundsException nếu chỉ số không hợp lệ
                Logger.getLogger(QuanLiNhanVienView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_listAreaTableMouseClicked

    private void detailAreaAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailAreaAssignmentActionPerformed
        // TODO add your handling code here:

        ChiTietPhanCongKhuVucView detailAssignment = new ChiTietPhanCongKhuVucView();
        detailAssignment.setVisible(true);
    }//GEN-LAST:event_detailAreaAssignmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addArea;
    private javax.swing.JButton deleteArea;
    private javax.swing.JButton detailAreaAssignment;
    private javax.swing.JTextField fieldNameArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listAreaTable;
    private javax.swing.JButton reloadArea;
    private javax.swing.JButton updateArea;
    // End of variables declaration//GEN-END:variables
}
