/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.main.Manager;

import controllers.Manager.QuanLiNhanVienCtrl;
import controllers.Manager.QuanLiTrungGian;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.DataGlobal;
import models.NhanVienModel;
import models.TrungGianModel;

/**
 *
 * @author GIANG
 */
public class TrangTrungGian extends javax.swing.JFrame {

    /**
     * Creates new form TrangTrungGian
     */
    DefaultTableModel tableModel;
    List<TrungGianModel> listWorker = new ArrayList<>();

    private int selectedIndex;

    public TrangTrungGian() {
        try {
            initComponents();

            tableModel = (DefaultTableModel) listTrungGianTable.getModel();

            hienThiDSNhanVien();

            DeleteWorker.setEnabled(false);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLiNhanVienView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void hienThiDSNhanVien() throws ClassNotFoundException {

        listWorker = QuanLiTrungGian.timTatCaTrungGian();

        tableModel.setRowCount(0);

        listWorker.forEach(nv -> {
            tableModel.addRow(new Object[]{nv.getMATG(), nv.getTENTG(), nv.getTENCHITIET(), nv.getTGDANGKY()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AddWorker = new javax.swing.JButton();
        DeleteWorker = new javax.swing.JButton();
        ReloadPage = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTrungGianTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 239, 254));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(43, 54, 116));
        jLabel1.setText("Quản lí trung gian");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 205, 153));
        jLabel2.setText("Quản lí tiền nước công ti dịch vụ nước đô thị");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Danh sách trung gian");

        AddWorker.setBackground(new java.awt.Color(0, 153, 255));
        AddWorker.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddWorker.setForeground(new java.awt.Color(255, 255, 255));
        AddWorker.setText("Thêm trung gian");
        AddWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddWorkerActionPerformed(evt);
            }
        });

        DeleteWorker.setBackground(new java.awt.Color(0, 153, 255));
        DeleteWorker.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeleteWorker.setForeground(new java.awt.Color(255, 255, 255));
        DeleteWorker.setText("Xóa");
        DeleteWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteWorkerActionPerformed(evt);
            }
        });

        ReloadPage.setBackground(new java.awt.Color(0, 153, 255));
        ReloadPage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ReloadPage.setForeground(new java.awt.Color(255, 255, 255));
        ReloadPage.setText("Làm mới");
        ReloadPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadPageActionPerformed(evt);
            }
        });

        listTrungGianTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã trung gian", "Tên trung gian", "Địa chỉ", "Thời gian đăng ký"
            }
        ));
        listTrungGianTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTrungGianTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listTrungGianTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(AddWorker)
                        .addGap(103, 103, 103)
                        .addComponent(DeleteWorker)
                        .addGap(55, 55, 55)
                        .addComponent(ReloadPage)))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AddWorker)
                    .addComponent(ReloadPage)
                    .addComponent(DeleteWorker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddWorkerActionPerformed
        // TODO add your handling code here:
        // Tạo cửa sổ mới để nhập thông tin người dùng
        ThemTrungGian addUserWindow = new ThemTrungGian();

        // Hiển thị cửa sổ AddUser
        addUserWindow.setVisible(true);
        addUserWindow.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            hienThiDSNhanVien();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLiNhanVienView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddWorkerActionPerformed

    private void DeleteWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteWorkerActionPerformed
        // TODO add your handling code here:

        int selectedIndex = listTrungGianTable.getSelectedRow();

        if (selectedIndex >= 0) {
            String[] options = {"Đồng ý", "Thoát"};
            int option = JOptionPane.showOptionDialog(
                    this,
                    "Bạn có chắc muốn xóa trung gian này",
                    "Cảnh báo",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    options,
                    options[1]
            );

            if (option == 0) {
                try {
                    TrungGianModel trungGian = listWorker.get(selectedIndex);

                    QuanLiTrungGian.XoaTrungGian(trungGian.getMATG(), trungGian.getMACTVK());
                    hienThiDSNhanVien();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(QuanLiNhanVienView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_DeleteWorkerActionPerformed

    private void ReloadPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadPageActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            hienThiDSNhanVien();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLiNhanVienView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReloadPageActionPerformed

    private void listTrungGianTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTrungGianTableMouseClicked
        // TODO add your handling code here:
        DeleteWorker.setEnabled(true);

    }//GEN-LAST:event_listTrungGianTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangTrungGian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangTrungGian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangTrungGian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangTrungGian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangTrungGian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddWorker;
    private javax.swing.JButton DeleteWorker;
    private javax.swing.JButton ReloadPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listTrungGianTable;
    // End of variables declaration//GEN-END:variables
}
